name: Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 2: Log in to Docker Hub or other container registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/aprtmt-system-user-lifecycle:${GITHUB_SHA}"
          docker build -t $IMAGE_NAME .
          echo "DOCKER_IMAGE=$IMAGE_NAME" >> $GITHUB_ENV

      # Step 4: Push Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}   

      # Step 6: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # Step 7: Configure kubectl using kubeconfig
      - name: Configure Kubectl using kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # Step 8: Create Kubernetes secret for JWT_SECRET_KEY from GitHub Secrets
      - name: Create Kubernetes secret for JWT_SECRET_KEY
        run: |
          kubectl create secret generic jwt-secret \
            --from-literal=jwt-secret-key="${{ secrets.JWT_SECRET_KEY }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 9: Create Kubernetes secret for MYSQL_ROOT_PASSWORD from GitHub Secrets
      - name: Create Kubernetes secret for MYSQL_ROOT_PASSWORD
        run: |
          kubectl create secret generic mysql-root-secret \
            --from-literal=mysql-root-password="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 10: Apply Kubernetes file user-lifecycle-pipeline
      - name: Apply Kubernetes file user-lifecycle-pipeline
        run: |
          kubectl apply -f k8s/user-lifecycle-deployment.yml

      # Step 11: Update Deployment to use the new Docker image and deploy to AKS
      - name: Deploy user service to AKS
        run: |
          kubectl set image deployment/user-service user-service=${{ env.DOCKER_IMAGE }}
